import os



class RequestURL:
    def __init__(self):
        self.MEGA_URL_LIST_COMMAND_UNTESTED = os.environ.get('MEGA_URL_LIST_COMMAND_UNTESTED')
        self.MEGA_URL_COMMAND_UPDATE = os.environ.get('MEGA_URL_COMMAND_UPDATE')
        self.MEGA_URL_COMMAND_DETAIL = os.environ.get('MEGA_URL_COMMAND_DETAIL')
        self.URL_GET_DEVICE_DETAIL = os.environ.get('URL_GET_DEVICE_DETAIL')

        self.MEGA_URL_COMMANDLOG_GETBY_COMMANDID = os.environ.get('MEGA_URL_COMMANDLOG_GETBY_COMMANDID')
        self.MEGA_URL_COMMANDLOG_CREATE = os.environ.get('MEGA_URL_COMMANDLOG_CREATE')
        self.MEGA_URL_COMMANDLOG_UPDATE = os.environ.get('MEGA_URL_COMMANDLOG_UPDATE')

        self.MEGA_URL_LIST_ACTION_UNTESTED = os.environ.get('MEGA_URL_LIST_ACTION_UNTESTED')
        self.MEGA_URL_ACTION_UPDATE = os.environ.get('MEGA_URL_ACTION_UPDATE')
        self.MEGA_URL_ACTION_DETAIL = os.environ.get('MEGA_URL_ACTION_DETAIL')
        self.MEGA_URL_ACTIONLOG_GETBY_ACTIONID = os.environ.get('MEGA_URL_ACTIONLOG_GETBY_ACTIONID')
        self.MEGA_URL_ACTIONLOG_CREATE = os.environ.get('MEGA_URL_ACTIONLOG_CREATE')
        self.MEGA_URL_ACTIONLOG_UPDATE = os.environ.get('MEGA_URL_ACTIONLOG_UPDATE')


        self.MEGA_URL_LIST_TEMPLATE_UNTESTED = os.environ.get('MEGA_URL_LIST_TEMPLATE_UNTESTED')



